spring:
  profiles:
    active: dev
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false

jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad

logging:
  level:
    root: "warn"
    com.nwachukwufavour.dronetransport: "info"